title: 'Stefan Jaindl'
default_lang: de
author:
  name: 'Stefan Jaindl'
  email: jaindl.stefan@gmail.com
taxonomies:
  - category
  - tag
  - month
metadata:
  telephone: '+436641554623'
  homepage: www.stefan-jaindl.com
  street: 'Copacabana 54'
  zip: '8401'
  city: 'Kalsdorf bei Graz'
  resumeHeader: 'Welcome on my homepage! <br> Check out my pages: <br> <b> Resume - Projects - Blog - Travel </b>'
  abenteuerHeader: 'The world is a book and those who do not travel read only a page'
  blogHeader: 'Checkout blog posts about various topics helpful to software developers everyday life'
  projectsHeader: 'Overview over my personal projects with Android, iOS, Web Development and Data Structures & Algorithms'
  resumeImage: images/header-mask/header-mask-resume.jpeg
  meImage: images/header-mask/header-mask-resume-me.jpeg
  abenteuerImage: images/header-mask/header-mask-reisen.jpeg
  blogImage: images/header-mask/header-mask-blog.jpeg
  projectsImage: images/header-mask/header-mask-projects.jpeg
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  /changelog: /blog/the-urban-jungle
routes:
  /something/else: /blog/focus-and-blur
  '/another/one/(.*)': /blog/$1
blog:
  route: /blog
description: 'Software Engineer'
website: www.stefan-jaindl.com
address:
  -
    line: 'Copacabana 54'
  -
    line: '8401 Kalsdorf'
  -
    line: Austria
contact:
  -
    line: jaindl.stefan@gmail.com
  -
    line: '+43664/15 54 623'
