title: 'Stefan Jaindl'
default_lang: de
author:
  name: 'Stefan Jaindl'
  email: jaindl.stefan@gmail.com
taxonomies:
  - category
  - tag
metadata:
  telephone: +43664/1554623
  homepage: www.stefanjaindl.at
  street: 'Lilienthalstraße 9'
  zip: '9020'
  city: Klagenfurt
  resumeHeader: 'Herzlich Willkommen auf meiner Webseite! <br> Hier finden Sie eine Sammlung meiner Projekte, Blogposts und Reisen'
  abenteuerHeader: 'The world is a book and those who do not travel read only a page'
  hochzeitHeader: 'Der glanzvollste Moment in Ihrem Leben, wir halten diesen mit Fotos und Videos fest'
  zeitrafferHeader: 'Zeitraffer-Aufnahmen lassen die Zeit wie im Flug vergehen, als drehte sich die Welt plötzlich schneller.'
  resumeImage: images/header-mask/header-mask-resume.jpg
  abenteuerImage: images/header-mask/header-mask-reisen.jpeg
  hochzeitImage: images/header-mask/header-mask-hochzeitsvideos.jpeg
  zeitrafferImage: images/header-mask/header-mask-zeitraffer.jpeg
  iconHochzeit: images/misc/icon_rings.svg
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
description: 'Software Engineer'
website: getgrav.org
address:
  -
    line: 'Lilienthalstraße 9'
  -
    line: '9020 Klagenfurt'
  -
    line: 'Austria'
contact:
  -
    line: jaindl.stefan@gmail.com
  -
    line: '+43664/1554623'
  -
    line: 'www.linkedin.com/in/stefanjaindl'
  -
    line: 'https://github.com/sjaindl'