title: abenteuermagnet
default_lang: de
author:
  name: 'Walter Magnet'
  email: office@hochzeitvideo.at
taxonomies:
  - category
  - tag
metadata:
  telephone: '0664 38 67 173'
  homepage: www.abenteuermagnet.at
  street: 'Parkweg 9/8'
  zip: '9400'
  city: Wolfsberg
  abenteuerHeader: 'Herzlich Willkommen auf meiner Webseite! <br> Hier finden Sie eine Sammlung meiner Reisen, Projekten und Arbeiten'
  hochzeitHeader: 'Der glanzvollste Moment in Ihrem Leben, wir halten diesen mit Fotos und Videos fest'
  zeitrafferHeader: 'Zeitraffer-Aufnahmen lassen die Zeit wie im Flug vergehen, als drehte sich die Welt plötzlich schneller.'
  abenteuerImage: images/header-mask/header-mask-reisen.jpeg
  hochzeitImage: images/header-mask/header-mask-hochzeitsvideos.jpeg
  zeitrafferImage: images/header-mask/header-mask-zeitraffer.jpeg
  iconHochzeit: images/misc/icon_rings.svg
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
